version: '3'
services:
 plex:
  container_name: plex
  image: linuxserver/plex
  network_mode: host
  restart: unless-stopped
  ports:
   - 32400:32400
   - 32400:32400/udp
   - 32469:32469
   - 32469:32469/udp
   - 5353:5353/udp
   - 1900:1900/udp
  volumes:
   - /media-server/plex:/config
   - /data/tv-shows:/data/tvshows
   - /data-2/movies:/data/movies
   - /data-2/transcoding:/transcode
  environment:
   - PUID=${USERID}
   - PGID=${GROUPID}
   - TZ=${TIMEZONE}
   - VERSION=latest
  devices:
   - /dev/dri:/dev/dri
  privileged: true


 radarr:
  container_name: radarr
  image: linuxserver/radarr
  network_mode: host
  restart: unless-stopped
  ports:
   - 7878:7878
  volumes:
   - /media-server/radarr:/config
   - /data-2/bit-downloads:/downloads
   - /data-2/movies:/movies
  environment:
   - PUID=${USERID}
   - PGID=${GROUPID}
   - TZ=${TIMEZONE}

 sonarr:
  container_name: sonarr
  image: linuxserver/sonarr
  network_mode: host
  restart: unless-stopped
  ports:
   - 8989:8989
  volumes:
   - /media-server/sonarr:/config
   - /data-v2/bit-downloads:/downloads
   - /data-v2/tv-shows:/tv
  environment:
   - PUID=${USERID}
   - PGID=${GROUPID}
   - TZ=${TIMEZONE}

 transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - /media-server/transmission:/config
      - /data-v2/bit-downloads:/downloads
      - /data-v2/transmission-watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

 jackett:
  container_name: jackett
  image: linuxserver/jackett
  network_mode: host
  restart: unless-stopped
  ports:
   - 9117:9117
  volumes:
   - /media-server/jackett:/config
  environment:
   - PUID=${USERID}
   - PGID=${GROUPID}
   - TZ=${TIMEZONE}

 bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
    volumes:
      - /media-server/bazarr:/config
      - /data-2/movies:/movies
      - /data/tv-shows:/tv
    ports:
      - 6767:6767

 portainer:
  container_name: portainer
  image: portainer/portainer
  network_mode: host
  restart: unless-stopped
  ports:
   - 9000:9000
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - /media-server/portainer:/data
  environment:
   - PUID=${USERID}
   - PGID=${GROUPID}
   - TZ=${TIMEZONE}