version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    network_mode: host
    restart: unless-stopped
    ports:
     - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /mds-server-data/portainer:/data
    environment:
     - PUID=2658
     - TZ=America/Sao_Paulo