version: 2
services:
 portainer:
     container_name: portainer
     image: portainer/portainer
     network_mode: host
     restart: unless-stopped
     environment:
      - PGID=1001
      - PUID=2658
      - TZ=America/Sao_Paulo
     ports:
      - 9000:9000
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mds-server-data/portainer:/data

 netdata:
    image: netdata/netdata
    container_name: netdata
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PGID=997
      - PUID=2658
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro